### ISSUE TITLE
有人遇到吗

### ISSUE THREAD

**Issue by LUJYM** [guangqiang-liu/OneM#2]
一直加载本地 loading from localhost 8081 然后就出错了

**Comment by guangqiang-liu** [comment]
不好意思，才看到你的issue，你的问题解决了吗

**Comment by LUJYM** [comment]
@guangqiang-liu 你好 那个好像是服务器的问题 现在已解决 谢谢了

**Comment by guangqiang-liu** [comment]
恩恩，👌，解决了就好，谢谢支持
