### ISSUE TITLE
Android App 的音乐和图片这两个模块点击报错

### ISSUE THREAD

**Issue by Fritz-Xu** [guangqiang-liu/OneM#5]
如图，Android Studio打印如下

![image](https://user-images.githubusercontent.com/16849595/39121517-77dff71a-4724-11e8-8c0c-050656cf6c28.png)

**Comment by guangqiang-liu** [comment]
音乐报错是因为接口数据是趴的别人的数据，数据格式一变化了，这边项目就报错了，后面我做了修改，将音乐加载了本地的资源文件，这样就避免了别人的数据格式发生变化m图片报错也是接口的数据格式变更导致的，这种问题只能遇到报错在修复了，谢谢提示。
