### ISSUE TITLE
前辈，请问一下，运行项目报这个错是啥原因啊

### ISSUE THREAD

**Issue by wywzixin** [guangqiang-liu/OneM#7]
![image](https://user-images.githubusercontent.com/22430715/47276790-5a5f6700-d5ec-11e8-9257-f69e375c3ff0.png)

**Comment by gisert** [comment]
前辈，请问一下，运行项目报这个错是啥原因啊

**Comment by guangqiang-liu** [comment]
兄弟，issue 提重复了哈
