### ISSUE TITLE
前辈，请问一下，运行项目报这个错是啥原因啊

### ISSUE THREAD

**Issue by wywzixin** [guangqiang-liu/OneM#8]
![2018-10-22_111947](https://user-images.githubusercontent.com/22430715/47276810-8ed32300-d5ec-11e8-8a79-063b1e4bef93.png)

**Comment by guangqiang-liu** [comment]
你的这种报错，你检查下，是不是给组件对象塞值的时候写法不对，你百度下这个报错关键字，找找有没有能解决你的问题的
Objects are not valid as a React child

**Comment by wywzixin** [comment]
运行 OneM项目报的这个错，，，，我啥也没写

**Comment by guangqiang-liu** [comment]
这个就比较尴尬了啊，你那边报的这种错误，我这边运行了看了下，没有报错，我也不好帮你去定位你的工程那出现了问题，你这样好了，你把之前拉的代码删除了，然后重新 clone 个最新的代码试试看

**Comment by wywzixin** [comment]
嗯嗯，好的，谢谢强哥

**Comment by guangqiang-liu** [comment]
嗯嗯，不用客气啊，互相学习。
